[package]
name = "vildrose-isa"
description = "Instruction-set architecture definitions for Vildrose"

license-file = "LICENSES.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
vildrose-core = { workspace = true }

[lints]
workspace = true
