[package]
name = "hyldeblomst"
description = "Vildrose-VM - Not yet implemented"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
# Consider having some in the future

[dependencies]
vildrose-core = { workspace = true }
vildrose-isa = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
insta = { workspace = true }

[lints]
workspace = true
